export const CREATE_USER = "CREATE_USER";
export const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";
export const ADD_CART_ITEMS = "ADD_CART_ITEMS";
