export const CREATE_USER = "CREATE_USER";
export const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const ADD_CART_ITEMS = "ADD_CART_ITEMS";
export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE";
